replicaCount: 1

image:
  imageRegistry: "registry-2.yunna.net"
  repository: teamspeak
  tag: "3.13.7"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  ports:
    - name: voice
      port: 9987
      externalPort: 9987
      protocol: UDP
    - name: query
      port: 10011
      externalPort: 10011
      protocol: TCP
    - name: filetransfer
      port: 30033
      externalPort: 30033
      protocol: TCP

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

persistence:
  enabled: true
  path: /var/ts3server
  size: 5Gi

env:
  TS3SERVER_DB_PLUGIN: "ts3db_mysql"
  TS3SERVER_DB_SQLCREATEPATH: "create_mysql"
  TS3SERVER_DB_WAITUNTILREADY: "30"
  TS3SERVER_LICENSE: "accept"
  TS3SERVER_DB_HOST: "localhost"
  TS3SERVER_DB_NAME: "teamspeak"
  TS3SERVER_DB_PORT: "3306"
  TS3SERVER_DB_USER: "root"
  TS3SERVER_DB_PASSWORD: "password"
