replicaCount: 1

image:
  imageRegistry: "registry-2.yunna.net"
  repository: halohub/halo
  tag: "2.20"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP 
  port: 8090

resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 512Mi

persistence:
  enabled: true
  accessMode: ReadWriteOnce 
  size: 5Gi
  storageClass: "local"

env:
  env1:
    name: SPRING_PROFILES_ACTIVE
    value: "prod"
  env2:
    name: SERVER_PORT
    value: "8090"
  env3:
    name: HALO_WORK_DIR
    value: "/root/.halo2"
  env4:
    name: HALO_SECURITY_INITIALIZER_SUPERADMINUSERNAME
    value: "admin"
  env5:
    name: HALO_SECURITY_INITIALIZER_SUPERADMINPASSWORD
    value: "yunna@141"
  env7:
    name: TZ
    value: "Asia/Shanghai"