apiVersion: v1
kind: Service
metadata:
  name: {{ include "awvs.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "awvs.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 13443
  selector:
    app.kubernetes.io/name: {{ include "awvs.name" . }}
