replicaCount: 1

image:
  imageRegistry: registry-2.yunna.net
  repository: dyrnq/open-webui
  tag: "main"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      externalPort: 8080
      protocol: TCP

network:
  name: "1panel-network"
  external: true

env:
  OLLAMA_BASE_URL: "your_ollama_base_url"  # replace with actual value
  WEBUI_SECRET_KEY: "your_webui_secret_key"  # replace with actual value

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

labels:
  createdBy: "Apps"
