apiVersion: v1
kind: Service
metadata:
  name: {{ include "ubuntu-ssh.fullname" . }}
  labels:
    {{- include "ubuntu-ssh.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.env.env2.value }}  # 修改为使用 .Values.env.env2.value 来获取 SSH_PORT 配置
      targetPort: ssh
      protocol: TCP
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "ubuntu-ssh.selectorLabels" . | nindent 4 }}
