apiVersion: v1
kind: Service
metadata:
  name: {{ include "baseimage.fullname" . }}
  labels:
    {{- include "baseimage.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 22
  selector:
    {{- include "baseimage.selectorLabels" . | nindent 4 }}