apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "discourse.fullname" . }}
  labels:
    {{- include "discourse.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "discourse.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "discourse.labels" . | nindent 8 }}
        {{- include "discourse.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: discourse
          image: "{{ .Values.image.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - containerPort: 3000
          env:
            {{- if kindIs "array" .Values.env }}
            {{- range .Values.env }}
            - name: "{{ .name }}"
              value: "{{ .value }}"
            {{- end }}
            {{- else if kindIs "map" .Values.env }}
            {{- range $key, $value := .Values.env }}
            - name: "{{ $value.name }}"
              value: "{{ $value.value }}"
            {{- end }}
            {{- end }}
          resources:
            requests:
              memory: "{{ .Values.resources.requests.memory }}"
              cpu: "{{ .Values.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.resources.limits.memory }}"
              cpu: "{{ .Values.resources.limits.cpu }}"
          volumeMounts:
            - name: discourse-data
              mountPath: /bitnami/discourse
      volumes:
        - name: discourse-data
          persistentVolumeClaim:
            claimName: {{ include "discourse.fullname" . }}-pvc