apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "onlyoffice.fullname" . }}
  labels:
    {{- include "onlyoffice.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "onlyoffice.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "onlyoffice.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
            - name: data
              mountPath: /var/www/onlyoffice/Data # 默认持久化路径
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "onlyoffice.fullname" . }}-pvc
