replicaCount: 1

image:
  imageRegistry: "registry-2.yunna.net"
  repository: vaultwarden/server
  tag: "1.32.2-alpine"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  externalPort: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

persistence:
  enabled: true
  path: /data
  size: 5Gi

env:
  env1:
    name: ROCKET_PORT
    value: "80"
  env2:
    name: ROCKET_WORKERS
    value: "10"