apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudbeaver.fullname" . }}
  labels:
    {{- include "cloudbeaver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "cloudbeaver.selectorLabels" . | nindent 4 }}