apiVersion: v2
name: mysql
description: |
  MySQL 是世界上最流行的开源数据库之一。这个 Chart 提供了单节点的 MySQL 部署方案，
  适用于开发环境和小规模生产环境使用。提供资源限制、数据持久化等特性。
version: 0.1.0
appVersion: "8.0"
home: https://www.mysql.com/
sources:
  - https://github.com/mysql/mysql-server
maintainers:
  - name: "Your Name"
    email: "your.email@example.com"
annotations:
  "yunna.net/category": "Database"
  "yunna.net/category-zh": "数据库"
keywords:
  - "Database"
  - "MySQL"
  - "SQL"
  - "RDBMS"