apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pentest.fullname" . }}-sshd-config
  labels:
    {{- include "pentest.labels" . | nindent 4 }}
data:
  sshd_config: |
    Port 22
    Protocol 2
    HostKey /etc/ssh/ssh_host_rsa_key
    HostKey /etc/ssh/ssh_host_ecdsa_key
    HostKey /etc/ssh/ssh_host_ed25519_key
    PermitRootLogin yes
    PubkeyAuthentication yes
    PasswordAuthentication yes
    ChallengeResponseAuthentication no
    UsePAM yes
    X11Forwarding yes
    PrintMotd no
    AcceptEnv LANG LC_*
    Subsystem sftp /usr/lib/openssh/sftp-server
