apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "halo.fullname" . }}
  labels:
    {{- include "halo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "halo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "halo.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8090
              protocol: TCP
          env:
            {{- if kindIs "map" .Values.env }}
            {{- range $key, $value := .Values.env }}
            - name: "{{ $value.name }}"
              value: "{{ $value.value }}"
            {{- end }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness  
              port: http
            initialDelaySeconds: 30
            periodSeconds: 5
          volumeMounts:
            - name: data
              mountPath: /root/.halo2
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "halo.fullname" . }}-pvc