apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chatgpt-next-web.fullname" . }}
  labels:
    {{- include "chatgpt-next-web.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.env.API_KEY | b64enc }}
  secret-key: {{ .Values.env.SECRET_KEY | b64enc }}