apiVersion: v1
kind: Service
metadata:
  name: {{ include "nextcloud.fullname" . }}
  labels:
    {{ include "nextcloud.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.port }}
  selector:
    app.kubernetes.io/name: {{ include "nextcloud.name" . }}
