replicaCount: 1

image:
  imageRegistry: "registry-2.yunna.net"
  repository: kalilinux/kali-rolling
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 22

resources:
  limits:
    cpu: 2000m
    memory: 4Gi
  requests:
    cpu: 1000m
    memory: 2Gi

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 20Gi
  storageClass: "local"

env:
  env1:
    name: TZ
    value: "Asia/Shanghai"