apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudreve.fullname" . }}
  labels:
    {{- include "cloudreve.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cloudreve.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-{{ include "cloudreve.fullname" . }}
  labels:
    {{- include "cloudreve.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: 3306
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: {{ .Release.Name }}