apiVersion: v1
kind: Service
metadata:
  name: {{ include "open-webui.fullname" . }}
  labels:
    {{ include "open-webui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .externalPort }}
      targetPort: {{ .port }}
      protocol: {{ .protocol }}
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "open-webui.name" . }}
