apiVersion: v2
name: baseimage
description: |
  Phusion Baseimage 是一个特殊的 Docker 基础镜像，经过修改的 Ubuntu 系统，专为 Docker 容器设计。它包含了 init 进程和系统服务管理功能。
version: 0.1.0
appVersion: "latest"
home: https://github.com/phusion/baseimage-docker
sources:
  - https://github.com/phusion/baseimage-docker
maintainers:
  - name: "Phusion"
    email: "info@phusion.nl"
annotations:
  "yunna.net/category": "Base Image"
  "yunna.net/category-zh": "基础镜像"
keywords:
  - "Base Image"
  - "Ubuntu"
  - "Init System"
  - "System Services"