{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "filebrowser.fullname" . }}-srv
  labels:
    {{- include "filebrowser.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.srvSize }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "filebrowser.fullname" . }}-config
  labels:
    {{- include "filebrowser.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.configSize }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
{{- end }}